export const worksData = [
  {
    name: "プロフィールサイト",
    url: "https://reproduct-cannnny.vercel.app/",
    img: "thumb-pf.webp",
    category: "模写",
    tag: ["HTML&CSS"],
    overview: "プログラミング学習の最初に制作した模写サイトです。",
  },
  {
    name: "モンハン弱点教えるくん",
    url: "https://mh-weak-info.vercel.app/",
    img: "thumb-mh.webp",
    category: "開発",
    tag: ["React", "microCMS"],
    overview:
      "「モンスターハンター」に登場するモンスターの弱点を検索できるWebアプリです。",
  },
  {
    name: "Hello Pawmo!",
    url: "https://hello-pawmo.vercel.app/",
    img: "thumb-hp.webp",
    category: "開発",
    tag: ["React"],
    overview: "「パモット」がメッセージに答えて挨拶してくれるWebアプリです。",
  },
  {
    name: "らぶぱも",
    url: "https://love-pawmi.vercel.app/",
    img: "thumb-lp.webp",
    category: "開発",
    tag: ["React", "Photoshop"],
    overview: "「パモ」のぬいぐるみをひたすら眺めるWebアプリです。",
  },
  {
    name: "Canipture!",
    url: "https://canipture.vercel.app/",
    img: "thumb-ca.webp",
    category: "開発",
    tag: ["React", "microCMS", "Swiper", "Illustrator"],
    overview: "ゲームのスクリーンショットを掲載したギャラリーです。",
  },
  {
    name: "きょう何食べる？",
    url: "https://whats-for-dinner-etjbd6z2s-cannnny.vercel.app/",
    img: "thumb-wd.webp",
    category: "開発",
    tag: ["React", "microCMS", "Framer Motion", "Jotai", "Illustrator"],
    overview: "気分に合わせて今日のご飯を提案してくれるWebアプリです。",
  },
  {
    name: "コーポレートサイト",
    url: "https://rp-bakery.vercel.app/",
    img: "thumb-rp.webp",
    category: "模写",
    tag: ["HTML&CSS", "JavaScript", "Photoshop", "Illustrator"],
    overview: "架空のパン屋のWebサイトとして制作しました。",
  },
  {
    name: "【製作中】商品紹介ページ",
    url: "#",
    img: "",
    category: "模写",
    tag: ["HTML&CSS", "JavaScript", "Photoshop", "Illustrator"],
    overview: "架空の清涼飲料水を紹介するWebサイトです。",
  },
];
